import React, { useState, useEffect } from 'react';
import { Modal, ScrollView, Alert } from 'react-native';
import {
  Box,
  Text,
  Button,
  TextField,
  DropdownSelector,
} from '@burma-inventory/ui-components';
import { useTranslation } from '../../../core/i18n/i18n';
import { database } from '../../../core/database/database';
import {
  sqliteSchema,
  Region,
  Township,
  Ward,
} from '@burma-inventory/shared-types';
import { mapRegion } from '../../../core/data/repositories';
import { useAuth } from '../../../core/auth/auth';

interface RegisterShopModalProps {
  visible: boolean;
  onClose: () => void;
  onRegister: (shopId: string) => void;
}

export const RegisterShopModal: React.FC<RegisterShopModalProps> = ({
  visible,
  onClose,
  onRegister,
}) => {
  const { t } = useTranslation();
  const { activeRep } = useAuth();

  const [step, setStep] = useState(1);
  const [name, setName] = useState('');
  const [streetAddress, setStreetAddress] = useState('');
  const [contactName, setContactName] = useState('');
  const [contactPhone, setContactPhone] = useState('');
  const [contactEmail, setContactEmail] = useState('');

  const [latitude, setLatitude] = useState('');
  const [longitude, setLongitude] = useState('');

  const [regions, setRegions] = useState<Region[]>([]);
  const [townships, setTownships] = useState<Township[]>([]);
  const [wards, setWards] = useState<Ward[]>([]);

  const [selectedRegionId, setSelectedRegionId] = useState('');
  const [selectedTownshipId, setSelectedTownshipId] = useState('');
  const [selectedWardId, setSelectedWardId] = useState('');

  const [loading, setLoading] = useState(false);

  // Load territories on mount/visibility change
  useEffect(() => {
    if (!visible) return;

    // Reset wizard fields when opened
    setStep(1);
    setName('');
    setStreetAddress('');
    setContactName('');
    setContactPhone('');
    setContactEmail('');
    setLatitude('');
    setLongitude('');
    setSelectedRegionId('');
    setSelectedTownshipId('');
    setSelectedWardId('');

    const loadData = async () => {
      try {
        const regs = await database.select().from(sqliteSchema.regions);
        const ts = await database.select().from(sqliteSchema.townships);
        const ws = await database.select().from(sqliteSchema.wards);

        setRegions(regs.map(mapRegion));
        setTownships(
          ts.map((t: $Any) => ({
            id: t.id,
            name: t.name,
            regionId: t.region_id,
            createdAt: t.created_at,
            updatedAt: t.updated_at,
          })),
        );
        setWards(
          ws.map((w: $Any) => ({
            id: w.id,
            name: w.name,
            address: w.address,
            townshipId: w.township_id,
            createdAt: w.created_at,
            updatedAt: w.updated_at,
          })),
        );
      } catch (err) {
        console.error('Failed to load territories for onboarding wizard:', err);
      }
    };

    loadData();
  }, [visible]);

  // Nested selection dependency: reset township/ward if region changes
  const handleRegionChange = (regId: string) => {
    setSelectedRegionId(regId);
    setSelectedTownshipId('');
    setSelectedWardId('');

    // Default coords based on region (derived)
    if (regId === 'region-yangon') {
      setLatitude('16.7794');
      setLongitude('96.1518');
    } else if (regId === 'region-mandalay') {
      setLatitude('21.9754');
      setLongitude('96.0838');
    } else {
      setLatitude('');
      setLongitude('');
    }
  };

  // Reset ward if township changes
  const handleTownshipChange = (townId: string) => {
    setSelectedTownshipId(townId);
    setSelectedWardId('');
  };

  // Filter options based on parent selectors
  const filteredTownships = townships.filter(
    (t) => t.regionId === selectedRegionId,
  );
  const filteredWards = wards.filter(
    (w) => w.townshipId === selectedTownshipId,
  );

  const regionOptions = regions.map((r) => ({ label: r.name, value: r.id }));
  const townshipOptions = filteredTownships.map((t) => ({
    label: t.name,
    value: t.id,
  }));
  const wardOptions = filteredWards.map((w) => ({
    label: w.name,
    value: w.id,
  }));

  const currentRegion = regions.find((r) => r.id === selectedRegionId);
  const currentTownship = townships.find((t) => t.id === selectedTownshipId);
  const currentWard = wards.find((w) => w.id === selectedWardId);

  // Address derived string
  const autoGeneratedAddress =
    currentRegion && currentTownship && currentWard
      ? `${streetAddress.trim() ? streetAddress.trim() + ', ' : ''}${currentWard.name}, ${currentTownship.name}, ${currentRegion.name}`
      : '';

  const handleNext = () => {
    if (step === 1) {
      if (!name.trim() || !contactName.trim() || !contactPhone.trim()) {
        Alert.alert(t('error'), t('validationErrorFillFields'));
        return;
      }
      setStep(2);
    } else if (step === 2) {
      if (
        !selectedRegionId ||
        !selectedTownshipId ||
        !selectedWardId ||
        !streetAddress.trim()
      ) {
        Alert.alert(t('error'), t('validationErrorFillFields'));
        return;
      }
      setStep(3);
    }
  };

  const handleBack = () => {
    if (step > 1) {
      setStep(step - 1);
    }
  };

  const handleRegister = async () => {
    if (
      !name.trim() ||
      !contactName.trim() ||
      !contactPhone.trim() ||
      !selectedRegionId ||
      !selectedTownshipId ||
      !selectedWardId ||
      !streetAddress.trim()
    ) {
      Alert.alert(t('error'), t('validationErrorFillFields'));
      return;
    }

    setLoading(true);
    const newShopId = 'shop-' + Math.random().toString(36).substring(2, 15);
    const latVal =
      parseFloat(latitude) ||
      (selectedRegionId === 'region-yangon' ? 16.7794 : 21.9754);
    const lngVal =
      parseFloat(longitude) ||
      (selectedRegionId === 'region-yangon' ? 96.1518 : 96.0838);

    const newShop = {
      id: newShopId,
      name: name.trim(),
      address: autoGeneratedAddress,
      latitude: latVal,
      longitude: lngVal,
      region_id: selectedRegionId,
      township_id: selectedTownshipId,
      ward_id: selectedWardId,
      assigned_rep_id: activeRep.id || 'rep-1',
      lifetime_value: 0,
      sentiment_trend: 'STABLE',
      price_book_id:
        selectedRegionId === 'region-yangon' ? 'pb-yangon' : 'pb-mandalay',
      price_tier: 'Retailer',
      created_at: Date.now(),
      updated_at: Date.now(),
    };

    const newContactId =
      'contact-' + Math.random().toString(36).substring(2, 15);
    const newContact = {
      id: newContactId,
      shop_id: newShopId,
      name: contactName.trim(),
      phone_number: contactPhone.trim(),
      email: contactEmail.trim() || null,
      is_primary: true,
      created_at: Date.now(),
      updated_at: Date.now(),
    };

    try {
      await database.insert(sqliteSchema.shops).values(newShop);
      await database.insert(sqliteSchema.contacts).values(newContact);
      console.log(
        '[RegisterShopModal] Successfully created shop & contact:',
        newShop,
        newContact,
      );
      onRegister(newShopId);
      onClose();
    } catch (e: $Any) {
      console.error('[RegisterShopModal] Failed to register client:', e);
      Alert.alert(t('error'), t('couldNotRegisterClient'));
    } finally {
      setLoading(false);
    }
  };

  return (
    <Modal visible={visible} transparent animationType="slide">
      <Box
        flex={1}
        style={{ backgroundColor: 'rgba(15, 23, 42, 0.7)' }}
        justifyContent="center"
        alignItems="center"
        px="m"
      >
        <Box
          p="m"
          width="100%"
          bg="cardBackground"
          style={{
            maxWidth: 500,
            maxHeight: '90%',
            borderRadius: 16,
            boxShadow: '0px 10px 25px rgba(0,0,0,0.3)',
            elevation: 10,
          }}
        >
          {/* Header */}
          <Box
            mb="m"
            borderBottomWidth={1}
            borderColor="borderColor"
            pb="s"
            flexDirection="row"
            justifyContent="space-between"
            alignItems="center"
          >
            <Box>
              <Text variant="title" color="brand">
                🏢 {t('registerClient')}
              </Text>
              <Text variant="caption" mt="xs">
                {t('stepOf')
                  .replace('{step}', step.toString())
                  .replace('{total}', '3')}
              </Text>
            </Box>
            <Box flexDirection="row" bg="borderColor" borderRadius="m" p="xs">
              <Box
                width={16}
                height={8}
                borderRadius="s"
                bg={step >= 1 ? 'brand' : 'secondaryBackground'}
                mr="xs"
              />
              <Box
                width={16}
                height={8}
                borderRadius="s"
                bg={step >= 2 ? 'brand' : 'secondaryBackground'}
                mr="xs"
              />
              <Box
                width={16}
                height={8}
                borderRadius="s"
                bg={step >= 3 ? 'brand' : 'secondaryBackground'}
              />
            </Box>
          </Box>

          <ScrollView style={{ flex: 1 }} showsVerticalScrollIndicator={false}>
            {step === 1 && (
              <Box mb="m">
                <Text variant="body" fontWeight="bold" mb="m">
                  {t('enterClientProfileInfo')}
                </Text>
                <TextField
                  label={t('clientShopName')}
                  placeholder={t('clientNamePlaceholder')}
                  value={name}
                  onChangeText={setName}
                />

                <Box height={16} />

                <TextField
                  label={t('contactPersonName')}
                  placeholder={t('contactNamePlaceholder')}
                  value={contactName}
                  onChangeText={setContactName}
                />

                <Box height={16} />

                <TextField
                  label={t('contactPhoneNumber')}
                  placeholder={t('phonePlaceholder')}
                  value={contactPhone}
                  onChangeText={setContactPhone}
                />

                <Box height={16} />

                <TextField
                  label={t('emailOptional')}
                  placeholder={t('emailPlaceholder')}
                  value={contactEmail}
                  onChangeText={setContactEmail}
                />
              </Box>
            )}

            {step === 2 && (
              <Box mb="m">
                <Text variant="body" fontWeight="bold" mb="m">
                  {t('configureTerritoryDetails')}
                </Text>

                <DropdownSelector
                  label={t('region')}
                  selectedValue={selectedRegionId}
                  onValueChange={handleRegionChange}
                  options={regionOptions}
                  placeholder={t('selectRegionPlaceholder')}
                />

                <Box height={16} />

                <DropdownSelector
                  label={t('township')}
                  selectedValue={selectedTownshipId}
                  onValueChange={handleTownshipChange}
                  options={townshipOptions}
                  placeholder={t('selectTownship')}
                  disabled={!selectedRegionId}
                />

                <Box height={16} />

                <DropdownSelector
                  label={t('ward')}
                  selectedValue={selectedWardId}
                  onValueChange={setSelectedWardId}
                  options={wardOptions}
                  placeholder={t('selectWard')}
                  disabled={!selectedTownshipId}
                />

                <Box height={16} />

                <TextField
                  label={t('streetAddressDetails')}
                  placeholder={t('streetAddressPlaceholder')}
                  value={streetAddress}
                  onChangeText={setStreetAddress}
                  editable={!!selectedWardId}
                />

                <Box height={16} />

                <Box
                  p="s"
                  bg="secondaryBackground"
                  borderRadius="s"
                  borderWidth={1}
                  borderColor="borderColor"
                >
                  <Text variant="caption" color="secondaryText">
                    {t('addressPreview')}
                  </Text>
                  <Text variant="body" fontWeight="bold" color="brand" mt="xs">
                    📍 {autoGeneratedAddress || t('selectTerritoryAbove')}
                  </Text>
                </Box>
              </Box>
            )}

            {step === 3 && (
              <Box
                mb="m"
                p="s"
                bg="secondaryBackground"
                borderRadius="m"
                borderWidth={1}
                borderColor="borderColor"
              >
                <Text variant="body" fontWeight="bold" mb="m">
                  {t('reviewConfirmDetails')}
                </Text>
                <Box mb="s">
                  <Text variant="caption" color="secondaryText">
                    {t('clientName')}
                  </Text>
                  <Text variant="body" fontWeight="bold" mt="xs">
                    {name}
                  </Text>
                </Box>
                <Box mb="s">
                  <Text variant="caption" color="secondaryText">
                    {t('primaryContact')}
                  </Text>
                  <Text variant="body" mt="xs">
                    {contactName} ({contactPhone})
                  </Text>
                  {contactEmail ? (
                    <Text variant="caption" color="secondaryText">
                      {contactEmail}
                    </Text>
                  ) : null}
                </Box>
                <Box mb="s">
                  <Text variant="caption" color="secondaryText">
                    {t('assignedRegion')}
                  </Text>
                  <Text variant="body" mt="xs">
                    {currentRegion?.name}
                  </Text>
                </Box>
                <Box mb="s">
                  <Text variant="caption" color="secondaryText">
                    {t('township')}
                  </Text>
                  <Text variant="body" mt="xs">
                    {currentTownship?.name}
                  </Text>
                </Box>
                <Box mb="s">
                  <Text variant="caption" color="secondaryText">
                    {t('ward')}
                  </Text>
                  <Text variant="body" mt="xs">
                    {currentWard?.name}
                  </Text>
                </Box>
                <Box mb="s">
                  <Text variant="caption" color="secondaryText">
                    {t('fullRegisteredAddress')}
                  </Text>
                  <Text variant="body" fontWeight="bold" color="brand" mt="xs">
                    📍 {autoGeneratedAddress}
                  </Text>
                </Box>
                <Box mb="s">
                  <Text variant="caption" color="secondaryText">
                    {t('gpsCoordinatesDerived')}
                  </Text>
                  <Text variant="body" mt="xs">
                    {latitude || '16.7794'}, {longitude || '96.1518'}
                  </Text>
                </Box>
                <Box>
                  <Text variant="caption" color="secondaryText">
                    {t('defaultPriceBookTier')}
                  </Text>
                  <Text
                    variant="body"
                    mt="xs"
                    style={{ textTransform: 'capitalize' }}
                  >
                    {selectedRegionId === 'region-yangon'
                      ? t('yangonRetailBook')
                      : t('mandalayWholesaleBook')}
                  </Text>
                </Box>
              </Box>
            )}
          </ScrollView>

          {/* Footer Controls */}
          <Box
            borderTopWidth={1}
            borderColor="borderColor"
            pt="m"
            flexDirection="row"
            justifyContent="space-between"
          >
            <Button
              title={step === 1 ? t('cancel') : t('back')}
              variant="secondary"
              onPress={step === 1 ? onClose : handleBack}
            />
            {step < 3 ? (
              <Button
                title={t('nextBtn')}
                variant="primary"
                onPress={handleNext}
              />
            ) : (
              <Button
                title={t('registerBtn')}
                variant="primary"
                onPress={handleRegister}
                isLoading={loading}
              />
            )}
          </Box>
        </Box>
      </Box>
    </Modal>
  );
};
