import React, { useState, useEffect } from 'react';
import { ScrollView, Alert } from 'react-native';
import {
  Box,
  Text,
  Button,
  DropdownSelector,
  ModalSheet,
} from '@burma-inventory/ui-components';
import { useTranslation } from '../../../core/i18n/i18n';
import { database } from '../../../core/database/database';
import {
  sqliteSchema,
  Region,
  Township,
  Ward,
  Shop,
} from '@burma-inventory/shared-types';
import { mapRegion } from '../../../core/data/repositories';
import { eq } from 'drizzle-orm';

interface UpdateTerritoryModalProps {
  visible: boolean;
  onClose: () => void;
  shop: Shop;
  onUpdateSuccess: () => void;
}

const MODAL_MAX_WIDTH = 450;

export const UpdateTerritoryModal: React.FC<UpdateTerritoryModalProps> = ({
  visible,
  onClose,
  shop,
  onUpdateSuccess,
}) => {
  const { t } = useTranslation();

  const [regions, setRegions] = useState<Region[]>([]);
  const [townships, setTownships] = useState<Township[]>([]);
  const [wards, setWards] = useState<Ward[]>([]);

  const [selectedRegionId, setSelectedRegionId] = useState('');
  const [selectedTownshipId, setSelectedTownshipId] = useState('');
  const [selectedWardId, setSelectedWardId] = useState('');

  const [loading, setLoading] = useState(false);

  // Load territories and initialize values
  useEffect(() => {
    if (!visible) return;

    setSelectedRegionId(shop.regionId || '');
    setSelectedTownshipId(shop.townshipId || '');
    setSelectedWardId(shop.wardId || '');

    const loadData = async () => {
      try {
        const regs = await database.select().from(sqliteSchema.regions);
        const ts = await database.select().from(sqliteSchema.townships);
        const ws = await database.select().from(sqliteSchema.wards);

        setRegions(regs.map(mapRegion));
        setTownships(
          ts.map((t: $Any) => ({
            id: t.id,
            name: t.name,
            regionId: t.region_id,
            createdAt: t.created_at,
            updatedAt: t.updated_at,
          })),
        );
        setWards(
          ws.map((w: $Any) => ({
            id: w.id,
            name: w.name,
            townshipId: w.township_id,
            createdAt: w.created_at,
            updatedAt: w.updated_at,
          })),
        );
      } catch (err) {
        console.error('Failed to load territories for editor modal:', err);
      }
    };

    loadData();
  }, [visible, shop]);

  // Reset township/ward if region changes
  const handleRegionChange = (regId: string) => {
    setSelectedRegionId(regId);
    setSelectedTownshipId('');
    setSelectedWardId('');
  };

  // Reset ward if township changes
  const handleTownshipChange = (townId: string) => {
    setSelectedTownshipId(townId);
    setSelectedWardId('');
  };

  const filteredTownships = townships.filter(
    (t) => t.regionId === selectedRegionId,
  );
  const filteredWards = wards.filter(
    (w) => w.townshipId === selectedTownshipId,
  );

  const regionOptions = regions.map((r) => ({ label: r.name, value: r.id }));
  const townshipOptions = filteredTownships.map((t) => ({
    label: t.name,
    value: t.id,
  }));
  const wardOptions = filteredWards.map((w) => ({
    label: w.name,
    value: w.id,
  }));

  const currentRegion = regions.find((r) => r.id === selectedRegionId);
  const currentTownship = townships.find((t) => t.id === selectedTownshipId);
  const currentWard = wards.find((w) => w.id === selectedWardId);

  const autoGeneratedAddress =
    currentRegion && currentTownship && currentWard
      ? `${currentWard.name}, ${currentTownship.name}, ${currentRegion.name}`
      : shop.address;

  const handleSave = async () => {
    if (!selectedRegionId || !selectedTownshipId || !selectedWardId) {
      Alert.alert(t('error'), t('validationErrorFillFields'));
      return;
    }

    setLoading(true);
    try {
      await database
        .update(sqliteSchema.shops)
        .set({
          region_id: selectedRegionId,
          township_id: selectedTownshipId,
          ward_id: selectedWardId,
          address: autoGeneratedAddress,
          updated_at: Date.now(),
        })
        .where(eq(sqliteSchema.shops.id, shop.id));

      onUpdateSuccess();
      onClose();
      Alert.alert(t('success'), t('territoryUpdatedSuccess'));
    } catch (e: $Any) {
      console.error(
        '[UpdateTerritoryModal] Failed to update shop territory:',
        e,
      );
      Alert.alert(t('error'), t('territoryUpdateFailed'));
    } finally {
      setLoading(false);
    }
  };

  return (
    <ModalSheet
      visible={visible}
      onRequestClose={onClose}
      maxWidth={MODAL_MAX_WIDTH}
      animationType="slide"
    >
      <Box p="m">
        {/* Header */}
        <Box mb="m" borderBottomWidth={1} borderColor="borderColor" pb="s">
          <Text variant="title" color="brand">
            🗺️ {t('updateTerritory')}
          </Text>
          <Text variant="caption" mt="xs">
            {t('configureTerritoryHierarchyFor', { name: shop.name })}
          </Text>
        </Box>

        <ScrollView
          style={{ minHeight: 200, maxHeight: 400 }}
          showsVerticalScrollIndicator={false}
        >
          <Box mb="m">
            <DropdownSelector
              label={t('region')}
              selectedValue={selectedRegionId}
              onValueChange={handleRegionChange}
              options={regionOptions}
              placeholder={t('selectRegionPlaceholder')}
            />

            <Box height={16} />

            <DropdownSelector
              label={t('township')}
              selectedValue={selectedTownshipId}
              onValueChange={handleTownshipChange}
              options={townshipOptions}
              placeholder={t('selectTownship')}
              disabled={!selectedRegionId}
            />

            <Box height={16} />

            <DropdownSelector
              label={t('ward')}
              selectedValue={selectedWardId}
              onValueChange={setSelectedWardId}
              options={wardOptions}
              placeholder={t('selectWard')}
              disabled={!selectedTownshipId}
            />

            {selectedRegionId && selectedTownshipId && selectedWardId ? (
              <Box
                mt="m"
                p="s"
                bg="secondaryBackground"
                borderRadius="s"
                borderWidth={1}
                borderColor="borderColor"
              >
                <Text variant="caption" color="secondaryText">
                  {t('autoGeneratedAddress')}
                </Text>
                <Text variant="body" fontWeight="bold" color="brand" mt="xs">
                  📍 {autoGeneratedAddress}
                </Text>
              </Box>
            ) : null}
          </Box>
        </ScrollView>

        {/* Footer Controls */}
        <Box
          borderTopWidth={1}
          borderColor="borderColor"
          pt="m"
          flexDirection="row"
          justifyContent="space-between"
        >
          <Button title={t('cancel')} variant="secondary" onPress={onClose} />
          <Button
            title={t('save')}
            variant="primary"
            onPress={handleSave}
            isLoading={loading}
          />
        </Box>
      </Box>
    </ModalSheet>
  );
};
